config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'sessions#new'

  get 'user/new'

  # get 'sessions/login'

  get 'sessions/pieces'

  get 'sessions/home'

  get 'sessions/profile'

  get 'sessions/setting'

  get 'logout', to: 'sessions#destroy'

  get  '/signup',  to: 'users#new'
  get  '/pieces', to: 'pieces#index'

  post '/sessions/login', to: 'sessions#login_attempt'
  # to: 'pieces#index'

  resources :users


  resources :comments

  resources :pieces do
    resources :comments
  end


  get '/comments' => 'pieces#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :piece
  validates :comment, length: { minimum: 2 }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
   @page = (params[:page] || 1).to_i
   skip = (@page - 1) * 25
   @comments = Comment.order(created_at: :desc).limit(25).offset(skip).all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)
    respond_to do |format|
      if @comment.save
        saved = true
        format.html { redirect_back fallback_location: 'pieces/#{@comment.piece_id}', status: 302 }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:comment, :piece_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2>Where's your comment?</h2>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :comment, style: "display:none;" %>
    <%= form.text_area :comment, id: :comment_comment %>
  </div>
  <% id ||= false %>
  <div class="field">
    <% if id != false %>
    <%= form.label :piece_id, style: "display:none;" %>

      <%= form.text_field :piece_id, id: :comment_piece_id, value: id, style: "display:none;" %>
    <% else %>
      <%= form.label :piece_id, style: "display:none;" %>
      <%= form.text_field :piece_id, id: :comment_piece_id, style: "display:none;" %>
    <% end %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', pieces_path %>

app/views/comments/index.html.erb
<style>
body {
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
}

.navbar.navbar-toggleable-md.navbar-light {
  width: 100%;
}

h1 {
  padding-bottom: 1em;
}

.two {
  padding-left: 1em;
  padding-right: 1em;
}

ul.navbar-nav {
  margin-left: 550px;
}

.comments {
  visibility: hidden;
}

.btn-block {
  border: 0.5px black solid;
}
</style>

<p id="notice"><%= notice %></p>

<h1>Latest Comments</h1>

<table>
  <thead>
    <tr>
      <th>Comment</th>
      <th class="two">Piece</th>
      <th class="two"> Created </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td>"<%= comment.comment %>"</td>
        <td class="two"><%= comment.piece.title %></td>
        <td class="two"> <%= time_ago_in_words(comment.created_at) %> ago</td>
        <td><button class="btn btn-secondary"><%= link_to 'See', comment.piece %></button></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<button class="btn btn-block"><%= link_to 'Home', '/pieces' %></button>

app/views/comments/new.html.erb
<style>
h2, li {
  color: red;
}

.nav-item {
  padding-left: 550px;
}

.main {
  display: flex;
  align-content: center;
  justify-content: center;
  flex-direction: column;
  align-items: center;
}

textarea {
  padding-left: 10em;
}

.actions {
  display: flex;
  justify-content: center;
}

input {
  margin-bottom: 0.5em;
}
</style>

<div class="main">
  <div>
    <h1>New Comment</h1>
  </div>
  <div>
    <%= render 'form', comment: @comment %>
  </div>
  <div>
    <button class="btn"><%= link_to 'Back', piece_path(@comment.piece_id) %></button>
  </div>
</div>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Comment:</strong>
  <%= @comment.comment %>
</p>

<p>
  <strong>Piece:</strong>
  <%= @comment.piece.title %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', pieces_path %>